Fix some more commonly found issues
nullworks/cathook pull request #1095
Opened 2020-08-23 11:45 UTC by BenCat07

E.g. snap after closing menu, Projectile aimbot not compensating for ping (Tested to be needed), and Aimbot shooting at walls with projectiles/Not shooting when it should be able to.

2020-08-31 21:33 UTC, TotallyNotElite requested changes

2020-08-31 21:33 UTC, TotallyNotElite commented on src/hacks/Aimbot.cpp
> +    Vector predicted_origin = PredictEntity(entity);
Why does this variable exist

2020-08-31 21:33 UTC, TotallyNotElite commented on src/helpers.cpp
> +        auto angle = GetAimAtAngles(g_pLocalPlayer->v_Eye, endpos, LOCAL_E);
Why does this variable exist

2020-08-31 21:39 UTC, TotallyNotElite requested changes

2020-08-31 21:39 UTC, TotallyNotElite commented on src/hacks/Aimbot.cpp
>                  preferred = hitbox_t::hip_L;
Why exactly should the rocket launcher NOT aim at someone's feet?

2020-09-01 14:30 UTC, TotallyNotElite commented
Writing a message here because the GitHub bot refuses to notify anyone about reviews.

2020-09-01 15:11 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
>                  preferred = hitbox_t::hip_L;
Midair we aim at hip due to it being more centered and easier to hit that way

2020-09-01 15:11 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> +    Vector predicted_origin = PredictEntity(entity);
Because i forgot to use it

2020-09-01 15:11 UTC, BenCat07 commented on src/helpers.cpp
> +        auto angle = GetAimAtAngles(g_pLocalPlayer->v_Eye, endpos, LOCAL_E);
same as above

2020-09-01 15:14 UTC, TotallyNotElite commented on src/hacks/Aimbot.cpp
>                  preferred = hitbox_t::hip_L;
Uh? Where is the midair check please?

2020-09-01 15:19 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
>                  preferred = hitbox_t::hip_L;
immediately below.

2020-09-01 15:19 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
>                  preferred = hitbox_t::hip_L;
```            // Airborn projectile
            if (GetWeaponMode() == weaponmode::weapon_projectile)
            {
                if (g_pLocalPlayer->weapon()->m_iClassID() != CL_CLASS(CTFCompoundBow))
                {
                    bool ground = CE_INT(target, netvar.iFlags) & (1 << 0);
                    if (!ground)
                        preferred = hitbox_t::spine_3;
                }
            }```

2020-09-01 15:20 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
>                  preferred = hitbox_t::hip_L;
Wait, why does it aim at hip_l if they are grounded

2020-09-05 14:03 UTC, TotallyNotElite approved these changes

2020-09-05 15:37 UTC, merged

2021-06-15 23:12 UTC, acidtripparty commented on src/helpers.cpp
> +        vecOffset = Vector(23.5f, -8.0f, -3.0f);
How did you obtain the offsets over here? @BenCat07