Add Doubletap
nullworks/cathook pull request #1125
Opened 2020-10-12 22:08 UTC by BenCat07

I guess i somehow made it work?

2020-10-12 22:17 UTC, BenCat07 commented
The weapon shooting cooldowns are still a bit wonky, i'd recommend disabling "Only when can shoot" in aimbot.

2020-10-16 07:30 UTC, TotallyNotElite requested changes

2020-10-16 07:31 UTC, TotallyNotElite commented
Also, maybe doubleshot/doubletap is not the best term for this, since you can shoot more than twice

2020-10-16 15:00 UTC, BenCat07 commented on src/hacks/Warp.cpp
> +static int ticks_in_revved     = 0;
There is alot of jank related to how the game handles firing. Doubletap wall refuse to work if you spin up with m1, although it has the same state as m2 spinup. This is also a special case thing i will only use once, but yeah even if you spin up with m2 instead, you need to wait a bit after you spinned up to actually doubletap, it's extremely janky game mechanics.

2020-10-16 15:00 UTC, BenCat07 commented on src/hacks/Warp.cpp
> +bool shouldDoubleshot()
f

2020-10-16 15:00 UTC, BenCat07 commented on src/hacks/Warp.cpp
> +    if (in_doubletap)
yeah i'll take your commented suggestion and fix the naming

2020-10-16 18:20 UTC, BenCat07 commented
Renamed and fixed some really big issues

2020-10-17 17:30 UTC, notroboot approved these changes
Tested for a while and it seems to work well.

2020-10-21 18:35 UTC, TotallyNotElite approved these changes
You CANT make me review this code. I refuse. I demand a salary of 100k per year and benefits.

2020-10-22 09:39 UTC, merged