Fix true and enable aimbot to aim at npcs
nullworks/cathook pull request #1137
Opened 2020-10-20 12:52 UTC by BenCat07

This simply makes aimbot able to aim at npcs and the cheat will ignore players in truce.

2020-10-20 13:27 UTC, TotallyNotElite requested changes
Is there really no better way to determine truce?

2020-10-20 13:27 UTC, TotallyNotElite commented on src/PlayerTools.cpp
> +        return false;
I think this should be in shouldTarget instead of shouldTargetSteamId

2020-10-20 13:27 UTC, TotallyNotElite commented on src/hacks/Aimbot.cpp
> +        }
Does this code really need to be duplicated?

2020-10-20 20:24 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> +        }
talked out in dms, bt specific code exists

2020-10-21 11:50 UTC, BenCat07 commented
We have no other way to determine a truce.

2020-10-21 11:50 UTC, BenCat07 commented
the thing meant to tell us if there is a truce is broken and does not get networked

2020-10-21 18:31 UTC, TotallyNotElite requested changes
@BenCat07 did you even look at this code

2020-10-21 18:31 UTC, TotallyNotElite commented on src/hacks/ESP.cpp
> +    if (classid == CL_CLASS(CTFTankBoss) || classid == CL_CLASS(CMerasmus) || classid == CL_CLASS(CMerasmusDancer) || classid == CL_CLASS(CZombie) || classid == CL_CLASS(CEyeballBoss) || classid == C
This looks like duplicated code with Aimbot? Npc bool should also be checked first.

2020-10-21 18:31 UTC, TotallyNotElite commented on src/hacks/ESP.cpp
> +            AddEntityString(ent, horsemann_str, colors::FromRGBA8(0, 128, 0, 255));
Don't pull a Yanderedev. Switch case please!

2020-10-21 18:31 UTC, TotallyNotElite commented on src/hacks/ESP.cpp
> +    else if (classid == CL_CLASS(CHalloweenGiftPickup) && item_esp && item_gargoyle)
The item_esp bool is checked multiple times. Try to avoid this. Bool should also always be checked first, not the condition.

2020-10-21 18:31 UTC, TotallyNotElite commented on src/hacks/ESP.cpp
> +    else if (classid == CL_CLASS(CTFPumpkinBomb) && item_esp && item_pumpkinbomb)
The item_esp bool is checked multiple times. Try to avoid this. Bool should also always be checked first, not the condition.

2020-10-21 18:31 UTC, TotallyNotElite commented on src/itemtypes.cpp
> +    RegisterSpecialMapping([](CachedEntity *ent) -> bool { return ent->m_iClassID() == CL_CLASS(CTFAmmoPack) && !ITEM_CRUMPKIN; }, ITEM_AMMO_MEDIUM);
"!ITEM_CRUMPKIN" always resolves to false, therefore this lambda will always return false.

2020-10-21 19:05 UTC, BenCat07 commented
instant regret not looking at the code as it was said to be working

2020-10-21 19:06 UTC, BenCat07 commented on src/hacks/ESP.cpp
> +    if (classid == CL_CLASS(CTFTankBoss) || classid == CL_CLASS(CMerasmus) || classid == CL_CLASS(CMerasmusDancer) || classid == CL_CLASS(CZombie) || classid == CL_CLASS(CEyeballBoss) || classid == C
Will fix

2020-10-25 21:35 UTC, TotallyNotElite approved these changes

2020-10-25 21:35 UTC, merged