Added building condition esp
nullworks/cathook pull request #1158
Opened 2020-11-02 18:57 UTC by NotAnUser1

yeah thats it ig

2020-11-02 18:59 UTC, TotallyNotElite commented
I'll review this soont :tm:, please don't merge without my approval

2020-11-10 17:27 UTC, BenCat07 commented on src/hacks/ESP.cpp
> +            else if (classid == CL_CLASS(CObjectTeleporter) && CE_INT(ent, netvar.m_iTeleState) == 1 || (IsDisabled || IsPlasmaDisabled))
this should check state <= 1 (0 is disabled, 1 is idle aka unconnected)

2020-11-14 10:57 UTC, TotallyNotElite requested changes

2020-11-14 10:57 UTC, TotallyNotElite commented on src/hacks/ESP.cpp
> +                    AddEntityString(ent, controlled_str, colors::FromRGBA8(220.0f, 220.0f, 220.0f, 255.0f));
I don't think we should show this at all actually. You don't seem to use IsControlled anywhere else, so you should also remove the bool too.

```suggestion
```

2020-11-14 10:57 UTC, TotallyNotElite commented on src/hacks/ESP.cpp
> +            switch (classid)
Can you remove the useless curly brackets after the `case` statements?

2020-11-14 10:57 UTC, TotallyNotElite commented on include/core/netvars.hpp
> +/*
What even changed here?

2020-11-15 19:40 UTC, NotAnUser1 commented on src/hacks/ESP.cpp
> +                    AddEntityString(ent, controlled_str, colors::FromRGBA8(220.0f, 220.0f, 220.0f, 255.0f));
Sure, I can remove the bool but can I keep this in? imo it's pretty informative

2020-11-17 17:25 UTC, BenCat07 commented on src/hacks/ESP.cpp
> +                    AddEntityString(ent, controlled_str, colors::FromRGBA8(220.0f, 220.0f, 220.0f, 255.0f));
yes

2020-11-17 17:53 UTC, TotallyNotElite approved these changes
I'm trusting my previous review here, LGTM.

2020-11-17 17:53 UTC, merged