new default dominate says
nullworks/cathook pull request #1163
Opened 2020-11-13 18:31 UTC by meowinghuman

Saw a comment asking for new dominate says, well here ya go.

2020-11-14 11:04 UTC, TotallyNotElite requested changes

2020-11-14 11:04 UTC, TotallyNotElite commented on src/hacks/DominateSay.cpp
> +    "R.I.P %name%, they were fat, and died a virgin!",
I don't think this is github TOS compliant, we've been fck'd for killsays before:

![image](https://user-images.githubusercontent.com/38938720/99145690-22169f80-2671-11eb-879e-45ef7157a4a8.png)

2020-11-14 11:04 UTC, TotallyNotElite commented on src/hacks/DominateSay.cpp
> +    "Congrats %name%! You just won 50 precent off a free asswhoopin! Call now and get another one absolutely free!",
> You just won 50 precent off a **free**
You can't get 50 percent off something that is free

2020-11-14 11:10 UTC, G-4-M-3-R commented on src/hacks/DominateSay.cpp
> +    "Congrats %name%! You just won 50 precent off a free asswhoopin! Call now and get another one absolutely free!",
> You can't get 50 percent off something that is free

That just makes it better

2020-11-20 09:40 UTC, TotallyNotElite approved these changes

2020-11-20 09:41 UTC, merged