Added spies next to spy count
nullworks/cathook pull request #1164
Opened 2020-11-13 19:23 UTC by meowinghuman

Not really needed but I thought was somewhat cool.

2020-11-14 11:06 UTC, TotallyNotElite commented
@BenCat07 thoughts? I think this may be counterproductive because it may block up the center of the screen more.

2020-11-14 11:07 UTC, BenCat07 commented
Yeah may be, but i've not tested it yet

2020-11-22 15:31 UTC, BenCat07 requested changes

2020-11-22 15:31 UTC, BenCat07 commented on src/hacks/SpyAlert.cpp
> +            AddCenterString(format("BACKSTAB WARNING! ", (int) (closest_spy_distance / 64 * 1.22f), "m (", spy_count, " SPIES!", ")"), colors::red);
If you are going to add this, make it show SPY if there is a single one, and SPIES if there are multiple :)

2020-12-10 14:40 UTC, closed without merging