added, changed and corrected stuff
nullworks/cathook pull request #1165
Opened 2020-11-17 18:39 UTC by NotAnUser1

added option to show teammate buildings without enabling teammate (player) esp
added objectives esp
added disguised cond esp
corrected(?) vaccinator's resistance conds
changed explosive esp code to make it look neater
changed healthpack and ammopack code to make use of switch statements
changed vaccinator charges code to get rid of unneeded characters

2020-11-22 15:34 UTC, BenCat07 commented
Tell me once this is actually ready, right now you seem to still be adding stuff

2020-11-24 09:20 UTC, TotallyNotElite commented
this PR is hella broken, you need to rebase it

2020-11-24 12:11 UTC, TotallyNotElite requested changes

2020-11-24 12:11 UTC, TotallyNotElite commented on src/hacks/ESP.cpp
> +                                        AddEntityString(ent, charge + "% Uber | Charges: " + std::to_string((int) floor((CE_FLOAT(weapon, netvar.m_flChargeLevel) / 0.25f) * 100) / 100), colors::Healt
```suggestion
                                        AddEntityString(ent, charge + "% Uber | Charges: " + std::to_string((int) floor(CE_FLOAT(weapon, netvar.m_flChargeLevel) / 0.25f), colors::Health((CE_FLOAT(weapon, netvar.m_flChargeLevel) * 100), 100));
```

This makes more sense IMO

2020-11-24 12:11 UTC, TotallyNotElite commented on src/hacks/Misc.cpp
> +                AddSideString(format(info.name, " - (", observermode, ")"), color);
IMO this should not be changed. Current version is fine. Deathcam, freezcam, etc are not very useful

2020-11-24 12:11 UTC, TotallyNotElite commented on src/hacks/Radar.cpp
>                  return; // DEAD. not big surprise.
```suggestion
            if (ent->m_bAlivePlayer())
                return; // DEAD. not big surprise.
```

Not related to your code, but I still need to fix this

2020-11-25 19:52 UTC, TotallyNotElite commented on data/menu/nullifiedcat/visuals/esp.xml
> +            <AutoVariable width="fill" target="esp.item.objectives" label="Objectives" tooltip="Intels, carts and mvm bomb"/>
```suggestion
            <AutoVariable width="fill" target="esp.item.objectives" label="Objectives" tooltip="Intel, carts and mvm bombs"/>
```

Learn to grammar

2020-11-25 19:57 UTC, TotallyNotElite submitted a review, later dismissed

2020-11-25 20:14 UTC, TotallyNotElite approved these changes

2020-11-25 20:19 UTC, BenCat07 approved these changes
LGTM

2020-11-25 20:20 UTC, merged