updated resolver to be reversible, added bencat's nolerp
nullworks/cathook pull request #1166
Opened 2020-11-18 15:33 UTC by dotqurter

resolver works well enough, i should probably revert the nolerp settings, as it seemed to cause a massive frame drop but that may have just been a bug

2020-11-18 15:35 UTC, TotallyNotElite commented
Can you explain what this pull request tries to accomplish? What issue does this solve? Do you have an issue #?

2020-11-18 16:56 UTC, dotqurter commented
it fixes the resolver to use a more-proper bruteforce "algorithm" (if you wanna call it that)

2020-11-18 18:39 UTC, TotallyNotElite commented
There is definitely a lot more than that. Can you summarize the full functionality of this patch?

2020-11-18 18:50 UTC, BenCat07 commented on src/hacks/AntiAntiAim.cpp
> +        CE_VECTOR(player, netvar.m_angEyeAngles) = CE_VECTOR(player, netvar.m_angEyeAngles);
set to itself?

2020-11-18 20:07 UTC, dotqurter commented on src/hacks/AntiAntiAim.cpp
> +        CE_VECTOR(player, netvar.m_angEyeAngles) = CE_VECTOR(player, netvar.m_angEyeAngles);
yeah, it was the way i fixed the issue where it wouldn't disable after turning off

2020-11-18 20:08 UTC, dotqurter commented
> There is definitely a lot more than that. Can you summarize the full functionality of this patch?

there isn't much to it: the resolver part just makes a line from localplayer to enemyplayer, and uses bruteforce to tell which perpendicular angle to move the head to; so left or right

2020-11-18 20:10 UTC, TotallyNotElite commented
Oh I thought "resolver to be reversible" implied some new feature instead of improvements to the existing one. I'll take a look later.

2020-11-19 02:38 UTC, dotqurter commented
no, its a semi-joke because the last one that I had refused to disable if you turned off the feature, so you couldn't disable the resolver; this one actually works

2020-11-20 09:38 UTC, TotallyNotElite commented
Going to leave this review to @BenCat07 because he knows more about antiantiaim than me

2020-11-20 17:41 UTC, BenCat07 commented on src/hacks/AntiAntiAim.cpp
> +        auto &data  = resolver_map[player->player_info.friendsID];
This is unused

2020-11-20 17:42 UTC, BenCat07 commented on src/hacks/AntiAntiAim.cpp
> +                angle = 0;
This change looks good actually

2020-11-20 17:43 UTC, BenCat07 requested changes

2020-11-20 17:43 UTC, BenCat07 commented on src/hooks/visual/FrameStageNotify.cpp
> +static settings::Boolean nointerp_enabled("misc.animfix.nointerp", "false");
We should combine all of these including the original "animfix" into the nolerp variable, could you maybe do that for me? thanks

2020-11-22 11:27 UTC, BenCat07 commented
@dotqurter fyi i reviewed

2020-12-31 05:00 UTC, incontestableness commented
@dotqurter If you don't finish this I might get around to it eventually
@BenCat07 what's the nolerp fix do exactly? current nolerp sucks

2021-02-14 19:28 UTC, TotallyNotElite commented
Closing due to inactivity, feel free to reopen if interested.

2021-02-14 19:28 UTC, closed without merging