Add autoparty
nullworks/cathook pull request #1183
Opened 2020-11-28 20:54 UTC by delimeats-ch

cheemsburger gaming

2020-11-28 20:55 UTC, delimeats-ch commented
Untested, needs menu stuff still

2020-11-28 21:07 UTC, TotallyNotElite requested changes
Ok so a few more things:

- Instead of calling the engine for sending commands directly, you should use https://github.com/nullworks/cathook/blob/9c1b236a24db3a7324f5f4cbd374188efabd6e2a/src/hack.cpp#L105 instead.
- Instead of this "manual" configuration as provided by this module, what would you say about using the IPC for coordinating automatic leader selection, etc? Is that something you'd be interested in doing?

2020-11-28 21:07 UTC, TotallyNotElite commented on src/hacks/AutoParty.cpp
> +    EC::Register(EC::CreateMove, party_routine, "cm_autoparty", EC::average);
Createmove is not exactly ideal for this, because createmove **only works if you are in a game**. You should use EC::Paint instead (not to be confused with EC::Draw).

2020-11-28 21:18 UTC, delimeats-ch commented
>     * Instead of this "manual" configuration as provided by this module, what would you say about using the IPC for coordinating automatic leader selection, etc? Is that something you'd be interested in doing?

Not really, manual selection is a lot more versatile and not too hard to work with imo. Easy to make it work with premium bots or if you want to drag some bots around with you. I'll probably fix everything else.

2020-11-28 21:37 UTC, TotallyNotElite commented
Looks good :+1:! I'll accept and merge once it's tested and menu entries are added.

2020-11-29 23:46 UTC, delimeats-ch commented
Should be good to merge now

2020-11-30 04:24 UTC, delimeats-ch commented
One more thing to fix actually, setting party-hosts via `cat set` doesn't trigger the callback. Not sure how to fix that other than just loading it every time the routine runs, which feels kind of dumb.

2020-11-30 05:21 UTC, BenCat07 commented
well setting it via cat set should just trigger the callback

2020-11-30 05:23 UTC, delimeats-ch commented
Mind testing? Doesn't work for me, but editing it from the menu works fine

2020-11-30 05:24 UTC, BenCat07 commented
well if it didn't work then i'd be unable to enable/disable party bypas for example, but it works just fine soo

2020-11-30 05:27 UTC, delimeats-ch commented
Is the new value of a changed setting already reflected while the callback runs, or is the new value provided through the callback, and that needs to get passed in?

2020-11-30 05:28 UTC, delimeats-ch commented
e.g. `host_list.installChangeCallback([](settings::VariableBase<std::string> &var, std::string after) { repopulate(); });`
repopulate() assumes the new value is already in the setting

2020-11-30 05:29 UTC, delimeats-ch commented
I'll look tomorrow

2020-11-30 06:07 UTC, BenCat07 commented
> Is the new value of a changed setting already reflected while the callback runs, or is the new value provided through the callback, and that needs to get passed in?

undefined behaviour, use the `after` variable on callback

2020-11-30 09:18 UTC, TotallyNotElite commented
Actually, the behaviour is defined. The variable will always contain the OLD value until all other callbacks have been called.

2020-11-30 11:32 UTC, TotallyNotElite commented
This PR has kind of gone out of scope and includes changes that should probably be a separate PR. Also, you need to use the "after" variable like @BenCat07 said.

2020-11-30 17:25 UTC, delimeats-ch commented
> This PR has kind of gone out of scope and includes changes that should probably be a separate PR. Also, you need to use the "after" variable like @BenCat07 said.

ha ha development branch go brr
Fixed, ready for review.

2020-11-30 17:40 UTC, TotallyNotElite commented
Those are a lot of XML changes. We should try to see what formatting for spaces does instead.

2020-11-30 18:04 UTC, delimeats-ch commented
> Those are a lot of XML changes. We should try to see what formatting for spaces does instead.

Converting to spaces is a much smaller commit, want me to do that instead?

2020-11-30 18:04 UTC, TotallyNotElite commented
Sounds good, thanks

2020-11-30 18:54 UTC, delimeats-ch commented
> Sounds good, thanks

Done

2020-11-30 19:13 UTC, TotallyNotElite approved these changes
@BenCat07 review and merge

2020-12-03 16:14 UTC, TotallyNotElite commented
Pinging @BenCat07 again

2020-12-05 10:29 UTC, BenCat07 approved these changes

2020-12-06 14:39 UTC, merged

2020-12-06 14:40 UTC, TotallyNotElite commented
:tada: