Improve navbot patrol
nullworks/cathook pull request #1352
Opened 2021-02-14 17:31 UTC by aUniqueUser

- Fixes patrol getting stuck because it walks to area closest to localplayer causing it to walk between a couple nodes for a long time.
- Makes patrol stay nearby the enemy objective on payload and control points

2021-02-14 22:58 UTC, BenCat07 requested changes

2021-02-14 22:58 UTC, BenCat07 commented on src/hacks/NavBot.cpp
> +    // RED team, nav near enemy objective if possible
Logical flaw, some gamemodes have blue capture aswell.

2021-02-15 15:03 UTC, BenCat07 approved these changes
Approval of owner or @TotallyNotElite also needed, but LGTM

2021-02-16 07:19 UTC, BenCat07 approved these changes
LGTM

2021-02-16 10:46 UTC, TotallyNotElite approved these changes
lgtm

2021-02-16 10:46 UTC, merged