Improve autobackstab to use the swing trace provided by tf2
nullworks/cathook pull request #1359
Opened 2021-02-19 15:07 UTC by BenCat07

Also adds melee range modifier to melees

2021-02-19 18:19 UTC, TotallyNotElite requested changes

2021-02-19 18:19 UTC, TotallyNotElite commented on src/hacks/AutoBackstab.cpp
> +}
you've
got quite
a few
newlines
here

2021-02-19 18:19 UTC, TotallyNotElite commented on src/hacks/AutoBackstab.cpp
> -    }
Where did this code go

2021-02-20 12:58 UTC, BenCat07 commented on src/hacks/AutoBackstab.cpp
> -    }
i realized it's actually doing exactly nothing, since looking at the target origin is the best option, and if it does not work looking at the target origin, it just will not work in general, so this code is useless.

2021-02-20 12:59 UTC, BenCat07 commented on src/hacks/AutoBackstab.cpp
> +}
i had more code there before which i grouped, but i removed some parts that were unneeded, fixed to be grouped again properly

2021-02-20 16:24 UTC, BenCat07 commented on src/hacks/AutoBackstab.cpp
> -    }
correction, it does do something, in the case a targets origin is behind a wall, very much an edge case, but i fixed it anyways

2021-03-11 11:57 UTC, aUniqueUser approved these changes
Tested on TF2, LGTM

2021-03-13 21:45 UTC, TotallyNotElite approved these changes

2021-03-13 21:48 UTC, merged