#701 fix & gitignore changes
nullworks/cathook pull request #1421
Opened 2021-04-08 14:56 UTC by iraizo

This ignores any `.cache/*` files clangd creates, and stops the anti-aim from enabling 2 ticks after the grappling hook has been used, this has been tested and it is working.

2021-04-08 15:09 UTC, TotallyNotElite requested changes

2021-04-08 15:09 UTC, TotallyNotElite commented on src/hacks/AntiAim.cpp
> +    grapplinghook_ts = tickcount;
What is this? Why is this being set every time SendNetMessage is called? Why do you even need using_grapple and grapplinghook_ts? If using_grapple is true, just use `SetSafeSpace(int)` in cm. The way you did this is kinda stupid.

2021-04-08 15:09 UTC, TotallyNotElite commented on src/hacks/AntiAim.cpp
> +        using_grapple = false;
You don't need this, just set it to false in cm.

2021-04-08 15:09 UTC, TotallyNotElite commented on src/hacks/AntiAim.cpp
> +        if (tickcount - grapplinghook_ts <= 2)
grapplinghook_ts doesn't get updated if IN_ATTACK, so this doesn't work.

2021-04-08 15:09 UTC, TotallyNotElite commented on src/hooks/SendNetMsg.cpp
> +        if (hacks::shared::antiaim::isEnabled())
You should just check this in hacks::shared::antiaim::SendNetMessage.

2021-04-08 15:12 UTC, iraizo commented on src/hacks/AntiAim.cpp
> +    grapplinghook_ts = tickcount;
to be honest i rewrote this like 5 times and at the end of making the pr i didnt know what needed to be in there to even make it functional, gonna work on the changes now

2021-04-08 17:33 UTC, iraizo commented
okay apparently i dont know how to squash commits together, if merged please select `merge & squash`

2021-04-08 21:43 UTC, Trapacid commented
> This attempt at squashing commits is uhhh, debatable.

I told him what to do so he can merge my PR properly where I squashed it for him.

2021-04-08 21:59 UTC, TotallyNotElite commented
Do you... want me to help you?

2021-04-08 22:00 UTC, iraizo commented
> Do you... want me to help you?

yes git god

2021-04-09 13:36 UTC, BenCat07 requested changes

2021-04-09 13:36 UTC, BenCat07 commented on src/hacks/AntiAim.cpp
> +    if ((cmd->buttons & IN_ATTACK) && classid == CL_CLASS(CTFGrapplingHook) || (cmd->buttons & IN_ATTACK != g_pLocalPlayer->bAttackLastTick))
This if statement seems wrong, it should probably be

```if ((cmd->buttons & IN_ATTACK) && classid == CL_CLASS(CTFGrapplingHook) && !g_pLocalPlayer->bAttackLastTick)```

Else it will also run the code if you are just holding m1 and were not attacking last tick and it will also run the code if you just released m1

2021-04-09 14:29 UTC, BenCat07 requested changes
Do not remove the nullptr check. 
Let me point you to this.

https://github.com/TheAlePower/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/engine/pure_server.cpp#L328

Or do if you wish, decide yourself, TNE gave appproval.

2021-04-09 14:29 UTC, BenCat07 commented on src/hooks/SendNetMsg.cpp
> -            if ((KeyValues *) (((unsigned *) &msg)[4]))
*chuckles* I'm in danger.

2021-04-09 14:29 UTC, BenCat07 commented on src/hacks/AntiAim.cpp
> +    auto name = ((KeyValues *) (((unsigned *) &msg)[4]))->GetName();
*chuckles* I'm in danger.

2021-04-09 14:29 UTC, TotallyNotElite approved these changes
Can still think of an edge case or 2, but not caring is the better strategy here.

2021-04-09 14:29 UTC, TotallyNotElite commented on src/hooks/SendNetMsg.cpp
> -                ParseKeyValue((KeyValues *) (((unsigned *) &msg)[4]));
![image](https://user-images.githubusercontent.com/38938720/114195459-c4049480-9950-11eb-90e2-2ddbbae7229a.png)

2021-04-09 15:29 UTC, iraizo commented
I will readd it if needed in the evening, not sure why I removed that.

2021-04-10 10:51 UTC, TotallyNotElite commented
Probably a good call to readd it.

2021-04-10 22:23 UTC, iraizo commented
Good to go?

2021-05-05 10:40 UTC, BenCat07 commented on src/hacks/AntiAim.cpp
> +    auto name = ((KeyValues *) (((unsigned *) &msg)[4]))->GetName();
you forgot to fix this one, it still does not check if the keyvalues sent i nullptr

2021-05-06 20:28 UTC, BenCat07 approved these changes
LGTM

2021-05-06 20:28 UTC, merged