Playerlist and ESP changes
nullworks/cathook pull request #1426
Opened 2021-04-10 20:05 UTC by LightPower392

This pull request makes the playerlist sorted by team. It also changes the ESP by allowing a class icon where the emoji can be, allowing changes in bone thickness, separating corner width from corner height, and fixing performance issues that the emojis and bone ESP were having.
![ESP](https://user-images.githubusercontent.com/60998601/114283212-6f6b2300-99fd-11eb-8d65-77e1925ead65.png)

2021-04-10 20:24 UTC, iraizo commented on src/visual/menu/GuiInterface.cpp
>          if (name == "player_connect_client")
I know this wasnt in the PR but god damn why isnt this a switch statement

2021-04-10 20:49 UTC, iraizo requested changes
Features that work in this pull request:
 - Bone width
 - Playerlist sorting
 - Corner width and height
 - Projectile esp filtering
 - `esp.range` optimization
 
Features that are broken:
- [Sightlines](https://streamable.com/oqga53)
- [Class ESP](https://streamable.com/b8tbpb) (The same issue that light ESP has)
- [Tracers](https://streamable.com/zet4iu)

I have not reviewed the code quality.

2021-04-11 01:26 UTC, LightPower392 commented
I'll take a look at those

2021-04-12 17:05 UTC, LightPower392 commented
The tracer found in ESP was really only a repeat of the better version found under the tracers tab, so I merged the two of them. The only tracers are now found in the tab "Tracers"
The glitch with lightESP and the emojis was due to the way their distance size scaling was done, so I replaced that with a different way to scale their size that doesn't cause the glitch. Both are now combined under what is called "Head ESP"
I'm still trying to find out why the sightlines break so often.

2021-04-13 06:37 UTC, LightPower392 commented
As far as I can tell the issue with the sight lines is due to the game's fog-of-war system. When the sightline disappears, it's not that there was something wrong with the drawing, but rather that the ray trace fails altogether. If there is a fix to this, I'm not aware of it.

2021-04-17 14:33 UTC, TotallyNotElite commented
> As far as I can tell the issue with the sight lines is due to the game's fog-of-war system.

No, that's what happens when worldtoscreen returns false.

2021-04-17 17:36 UTC, LightPower392 commented
I don't think the problem has to do with WoldToScreen. I used `trace.m_pEnt` right after `g_ITrace->TraceRay` to test and found that the problem has to do with the trace ray. It also seems like the sightline only disappears if you look too far away from either the player or what they are looking at. Do you have an idea of what else this might be?

2021-04-17 18:08 UTC, TotallyNotElite commented
The behaviour you describe and the behaviour seen in the video perfectly matches what happens with worldtoscreen.

2021-04-17 18:35 UTC, BenCat07 commented
I am still confused what the issue exactly is. Send a screenshot of an example and i will fix it.

2021-04-17 20:48 UTC, LightPower392 commented
Irazio posted a video that shows the problem. The sightlines are often not displayed when they should be.

2021-04-28 23:17 UTC, LightPower392 commented
Any update @BenCat07 ?

2021-04-29 04:16 UTC, BenCat07 commented
had no time recently

2021-05-05 10:41 UTC, BenCat07 commented
I am working on this now.

2021-05-05 10:54 UTC, BenCat07 commented
This is missing GUI updates for the removed rvars, there is alot of red entries in the menu

2021-05-05 10:57 UTC, BenCat07 commented
Sightlines issue is caused by the marching length being halved, not the whole length of the sightline is being checked for the start position.

2021-05-05 11:22 UTC, BenCat07 commented
turns out the issue was an `>` being used instead of an `<`

2021-05-05 11:39 UTC, BenCat07 approved these changes
I fixed the remaining issues mentioned and tested if there were others.
LGTM.

2021-05-05 11:42 UTC, merged