Zoom sensitivity ratio tweak, header file modifications
nullworks/cathook pull request #1428
Opened 2021-04-15 00:54 UTC by Trapacid

Solves https://github.com/nullworks/cathook/issues/1427

Signed-off-by: Ashley <ash@trapacid.dev>

2021-04-15 00:55 UTC, iraizo submitted a review, later dismissed
LGTM

2021-04-15 04:20 UTC, LightPower392 commented
I think this should have been done differently. It always resets zoom_sensitivity_ratio to 1, even if the player had manually set it to a different value previously. It should also only change your sensitivity if "Remove scope" and "Remmove zoom/keep rifle" are enabled

2021-04-15 04:22 UTC, BenCat07 commented
It should probably be a seperate option aswell.

2021-04-15 04:27 UTC, BenCat07 requested changes

2021-04-15 04:27 UTC, BenCat07 commented on src/hooks/visual/OverrideView.cpp
> +            zoom_sensitivity_ratio->SetValue(1);
Does not reset to user defined Value.

2021-04-15 06:47 UTC, relaybots commented
I cannot tell you how long iv waited for this, but holy fuck is it good

2021-04-15 07:03 UTC, TotallyNotElite requested changes
Wtf

2021-04-15 08:33 UTC, iraizo commented
Getting value before setting it would fix the issue, no?

2021-04-15 08:47 UTC, BenCat07 commented
No, the code constantly sets sens, even if zoom state did not change at all. Please fix that.

2021-04-15 08:49 UTC, iraizo commented
Yeah I've talked to him about that, but didn't find a proper solution since I rather looked into something that only sets it's once Everytime you scope and not based on if the sensitivity changes

2021-04-15 08:53 UTC, BenCat07 commented
update on zoom state change instead of every tick

2021-04-15 18:29 UTC, LightPower392 commented
It still has the problems that `zoom_sens_fix` doesn't have actually have to be enabled for zoom_sensitivity_ratio to be changed. This is how I would have written this

    static auto zoom_sensitivity_ratio = g_ICvar->FindVar("zoom_sensitivity_ratio");
    
    if (g_pLocalPlayer->bZoomed)
    {
        // At least one of the three requirements are false, so user zoom_sensitivity_ratio will be reset to what they had it to
        if (!zoom_sens_fix || !no_zoom || !no_scope)
        {
            if (user_sensitivity_ratio_set)
                zoom_sensitivity_ratio_user = zoom_sensitivity_ratio->GetFloat();
            else
            {
                zoom_sensitivity_ratio->SetValue(zoom_sensitivity_ratio_user);
                user_sensitivity_ratio_set = true;
            }
        }
        // All three requirements are true, so change the zoom_sensitivity_ratio to 4
        else
        {
            zoom_sensitivity_ratio->SetValue(4);
                user_sensitivity_ratio_set = false;
        }
    }
And put this above `namespace hooked_methods`:
    `bool user_sensitivity_ratio_set = true;`
    `float zoom_sensitivity_ratio_user;`

2021-04-15 20:28 UTC, Trapacid commented
Thank you, @LightPower392 lmao.

Is that better?

2021-04-15 22:29 UTC, LightPower392 commented
That looks good except that you should probably update the tooltip for `Remove zoom/keep rifle` to reflect the change

2021-04-15 22:34 UTC, advance24th commented
im trying to compile these edits to cathooks 
and im getting an output at the end like 

```
make[3]: *** [CMakeFiles/cathook.dir/build.make:1805: CMakeFiles/cathook.dir/src/hooks/CreateMove.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:646: CMakeFiles/cathook.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:653: CMakeFiles/cathook.dir/rule] Error 2
make: *** [Makefile:182: cathook] Error 2
```

am i missing somthing?

2021-04-15 22:38 UTC, Trapacid commented
Edited the tooltip.

I did not modify CreateMove.cpp in any way. @advance24th

2021-04-15 22:39 UTC, advance24th commented
weird..

2021-04-15 22:41 UTC, advance24th commented
the error is

```
/home/notgonnagivemyname/cathook/src/hooks/CreateMove.cpp:307:25: error: ‘fakelag_midair’ was not declared in this scope
  307 |                     if (fakelag_midair && CE_INT(LOCAL_E, netvar.iFlags) & FL_ONGROUND)
      |                         ^~~~~~~~~~~~~~
```

2021-04-15 22:42 UTC, advance24th commented
everything till that code, was fine so i know its just this line of code

2021-04-15 22:43 UTC, Trapacid commented
Please create a separate issue for your compilation error.

2021-04-15 22:50 UTC, advance24th commented
please just this one question

is this [error fix(#1428)](https://github.com/nullworks/cathook/pull/1428) for the stable version of cathook?
or master(bleeding edge)?

2021-04-15 23:08 UTC, Trapacid commented
@advance24th Master, but do not use my branches/repo as they are not up to date with upstream.

If you wish to test this patch:
Clone the upstream repo in a test folder. Run `./config` and switch it to developer mode. Build and install cathook as normal with `./install-all`.
Then download the patch: `wget https://github.com/nullworks/cathook/commit/ea96ade96ae9a054f29bba15895686cd146923e7.patch`
Apply it with: `git apply ea96ade96ae9a054f29bba15895686cd146923e7.patch`
Run `make data && make`
Inject: `sudo ./attach`

2021-04-15 23:10 UTC, advance24th commented
Thanks ill try that, but for what i did before you commented was in this Issue ^^^^

2021-04-15 23:24 UTC, iraizo commented
Closes https://github.com/nullworks/cathook/issues/1427

2021-04-16 00:06 UTC, advance24th commented
> Closes #1427

i got it fixed anyways, goodbye and send this in regard to me

### Im dumb as fuck

2021-04-16 01:11 UTC, advance24th commented
wamo you delete my comment, about me saying im dumb

2021-04-17 11:58 UTC, relaybots commented
I hate yiu people who dare remove hate speech about me :(

2021-05-05 12:00 UTC, BenCat07 commented
Currently this:
- Breaks if you enable both rvars and zoom in before having zoomed in "normally" once (it will set the zoom sens to 0 once you use normal zooming)
- Constantly updates the sens while zoomed, even if the state didn't change

I fixed both those issues for you, so the pull request should be ready.

2021-05-05 12:01 UTC, BenCat07 approved these changes
LGTM

2021-05-08 11:54 UTC, merged