Abort if package manager fails and remove taunts on players
nullworks/cathook pull request #1460
Opened 2021-05-10 00:55 UTC by Zanthed

Aborting if package manager fails should prevent things like #1442 where the package manager fails to install a dependency, yet continues.

Removing taunts solve #953
Unknown if this actually fixes any sort of accuracy issue with conga. I don't see why it wouldn't though.

Signed-off-by: Ashley <zanthed@riseup.net>

2021-05-10 00:59 UTC, iraizo approved these changes
LGTM

I don't know if this fixes the inaccuracy issue but it does remove taunts

2021-05-10 05:05 UTC, BenCat07 requested changes
Please remove the "removes taunts" part. I have a more permanent fix coming with a future PR.

2021-05-10 18:45 UTC, Zanthed commented
Removed taunt removal.

2021-05-12 16:05 UTC, BenCat07 requested changes
There is an issue with this whole thing, if your updater is currently working (system update for example) or some package gets renamed, this whole script Will break completely, in the latter case bricking people's cathook install due to the git update being ran after dependencycheck.

2021-05-14 22:30 UTC, closed without merging