Add better Anti-aim options to HvH menu
nullworks/cathook pull request #1496
Opened 2021-06-26 03:06 UTC by SheepyChris

This pull request addresses a multitude of issues and complaints related to the functionality of Anti-aim in cathook. Previously you were not able to independently set fake and real angles for both pitch and yaw angles - this has now been solved with the creation of `antiaim.pitch.fake`, `antiaim.pitch.real`, `antiaim.yaw.fake` and `antiaim.yaw.real` with the additional static/custom values that can be set to each angle. 

![image](https://user-images.githubusercontent.com/12992355/123500092-7ae7e680-d609-11eb-91ba-25f7e0348f91.png)

I've been unable to test if fake yaw angles are working due to them not being visible in local servers (if that is what's happening), so I ask if anyone else could test them and determine that they're good to go for merging. I also apologize if the tab formatting looks different in GitHub, both Featherpad and Geany do that on my end.

2021-06-26 04:30 UTC, SheepyChris commented
It's been suggested in the Telegram that the switch logic for both yaw modes can be simplified - if the fake portion is confirmed to work I will also add that into the PR.

2021-06-26 04:35 UTC, SheepyChris commented
Was able to confirm in game that the fake portion works, if anyone has any better ideas to optimize the switch cases let me know.

2021-06-26 05:19 UTC, EngineerGaming69 commented
cathook is 5 years late on having good aa

2021-06-29 20:34 UTC, dankdonk commented
This is working well for me so far. Also, I don't know about geany but with vim you can just open a file and do
`:set expandtab`
`:set tabstop=4`
`:set shiftwidth=4`
`:retab`
to convert all the tabs to 4 spaces

2021-06-29 22:08 UTC, iraizo commented
> 
> 
> This is working well for me so far. Also, I don't know about geany but with vim you can just open a file and do
> `:set expandtab`
> `:set tabstop=4`
> `:set shiftwidth=4`
> `:retab`
> to convert all the tabs to 4 spaces

You can also just use clang format.

2021-07-03 07:35 UTC, BenCat07 requested changes
This works pretty well, atleast for the fake yaw part. Fake pitch part also works, but you've accidentally flipped the order, if fake and real pitch are enabled, others will see your real pitch, and your head is at your fake pitch, needs to be fixed.

2021-07-03 08:18 UTC, BenCat07 approved these changes
turns out i was just testing it in an unreliable environment.

2021-07-03 08:18 UTC, merged