Remove references to other games. Optimizations, fixes and some new features
nullworks/cathook pull request #1581
Opened 2021-11-12 18:25 UTC by ikeakayke

Removed references to other games, changed if to switch case where needed, added a few new features, relocated _bunnyhop_ code and renamed it _auto jump_
Removed Ignore Hoovy and Explosion Circles

2021-11-13 01:34 UTC, Zanthed commented
Reposted from last PR:

There are so many changes here that this really should have been split up by individual commits to make it a lot easier to review, debug, and test this. This just adds lots of difficulty here.
This is something that is going to need a lot of user testing.

Only things I've really noticed are the compiler options here.

Why are you removing `-march=native`? And using `-O3`?

There's no reason to force `-mavx2`. `-march=native` will automatically detect if a preset processor's CPU type if it supports AVX2 and optimise _**any code that uses AVX2**_. Especially since there are CPU specific optimisations out there and other quirks.

O3 isn't recommended unless carefully tested because it can cause compiler build issues, performance regressions such as excessive loop unrolling, or too much code being generated and making very large or bloated binaries; also causing a performance regression. This also makes debugging unnecessarily more difficult because it can be difficult to determine if a bug is from bad code, compiling with O3 in general, or code incompatible with O3.
There have been plenty of cases where O3 results in reduced math computational speeds as well, something software like this heavily relies on.
Cathook tries to support lots of hardware already.

2021-11-13 09:52 UTC, ikeakayke commented
`-march=native` does not always correctly detect if a CPU supports AVX2 or not. Yes, it is a rare occasion that I've only encountered a few times, but it is present. Every CPU made after 2013 supports AVX2. Users with a CPU that does not support AVX2 will need to edit CMakeLists.txt and change all the `-mavx2` arguments to `-march=native -mtune=native`. This information will need to be added to the README.md or to the wiki branch.
We have tested cathook with the `-O3` argument for 2 days now on 3 different computers, and there was no downgrade. As the argument states, the resulted code was more optimized from what we were able to observe. We invite you to test this yourself @Zanthed and write a description of what you were able to observe. If anything seemed to perform better, worse or had no impact at all.

2021-11-13 15:41 UTC, BenCat07 requested changes

2021-11-13 15:41 UTC, BenCat07 commented on src/crits.cpp
> +                                crit_string += std::to_string(int(info.m_flCritTime + 1.0f - g_GlobalVars->curtime)) + "s";
i'd like this to still have some floating point digits, yes currently it has to many, but it shouldn't just have none at all

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> -static settings::Boolean minigun_tapfire{ "aimbot.auto.tapfire", "false" };
Yes, minigun tapfire is a bit buggy with nospread, warp, etc, but it shouldn't just be removed

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> +        if (g_pLocalPlayer->spectator_state == g_pLocalPlayer->ANY)
Aimbot will enable when you are spectated in firstperson, but not if in thirdperson

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> +                DoAutoshoot();
Switching the order of these breaks melee aimbot entirely, since it never swings.

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> +                    DoAutoshoot(target_entity);
You cannot just force tapfire behaviour

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> +    if ((SERVER_TIME - last_mouse_check) < 0.02)
This may break some functionality while using warp, which affects player tickbase

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> +    if ((SERVER_TIME - last_mouse_check) < 0.02)
Same for anything replacing curtime with SERVER_TIME. There is a reason i adjust curtime in warp

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Aimbot.cpp
> +        float chargetime  = SERVER_TIME - chargebegin;
once again, replacing curtime with SERVER_TIME may cause issues due to warp/doubletap, leave it unchanged if possible.

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/CMakeLists.txt
> -            "${CMAKE_CURRENT_LIST_DIR}/ExplosionCircles.cpp"
This was actually useful though

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Misc.cpp
> -                    // And "Cyanide" for making it work with cathook.
Don't just remove the credits, i left them there for a reason.

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Misc.cpp
> +                static auto speedVar  = 6062.0f; // Engine limit on 3 axis, see: reddit.com/r/tf2/comments/57hhl4/question_is_there_a_maximum_rocket_jumping/d8t9x82
Needs to be properly tested, game itself does not use that value for calculation in AirMove, but instead m_flMaxspeed, as used before.

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Misc.cpp
> +    // Tauntslide needs improvement for movement, but it mostly works
could have just taken the old one then, no? It worked for not just forwards and backwards, but also sideways, unless this one is meant for different kinds of taunts?....

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Misc.cpp
> +        if (updateratetimer.test_and_set(500))
Adding this may cause issues with high latency and a ping not exactly 500ms away, it would bounce more, in theory.

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Misc.cpp
> +                case OBS_MODE_POI:
These are control points, or other "Points of interest" you can switch through, and would not be transmitted to us, as we are not the target

2021-11-13 15:41 UTC, BenCat07 commented on src/hacks/Misc.cpp
> +                case OBS_MODE_ROAMING:
Roaming has the same issue as above, it's when you can freely move in spec (e.g. on comm)

2021-11-13 15:53 UTC, ikeakayke commented on include/playerlist.hpp
> +    PAZER,
Soon to be added: Check chat for Pazer cheating accusation template and set the playing sending that message to PAZER. PAZER will then be treated as RAGE.

2021-11-13 15:56 UTC, ikeakayke commented on include/playerlist.hpp
> +    ABUSE,
Soon to be added: If betrayal limit is reached, then set to ABUSE, which will be treated as RAGE. The 2 lines 26 and 27 were left from something we weren't able to finish, but we will soon finish and make another pull request.

2021-11-16 00:33 UTC, TheCrazyInsanity commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20.4)
> Too high for Ubuntu, which is offically supported.

But does anybody really use ubuntu for this?

2021-11-16 05:09 UTC, Zanthed commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20.4)
> > Too high for Ubuntu, which is offically supported.
> 
> But does anybody really use ubuntu for this?

Not sure why whether "anybody uses it" is a concern. You can say the same thing about Gentoo support for Cathook; "Does anybody really use Gentoo for this?" Doesn't make sense.
Plenty of people use Ubuntu and want to use Ubuntu because it's super easy. Cathook officially supports Ubuntu.

2021-12-13 17:57 UTC, zelta01 commented
https://github.com/MistralDev/Mistral
yoinking unfinished code 😳 
![image](https://user-images.githubusercontent.com/64829585/145863524-a35a95ab-64b4-452c-b1a4-1efee3792bdb.png)
![image](https://user-images.githubusercontent.com/64829585/145863532-a5cfcaec-6869-48dc-a11b-e4672f3756e9.png)
[thats kinda sus](https://www.youtube.com/watch?v=0bZ0hkiIKt0)

2022-02-05 04:56 UTC, KyappyGR commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20.4)
> > Too high for Ubuntu, which is offically supported.
> 
> But does anybody really use ubuntu for this?

im using mint which is basically the same thing

2022-02-12 04:05 UTC, STG7754 commented
Aw hell OutOfFOVArrow.cpp got broken xd

2022-06-22 17:46 UTC, hellidox commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20.4)
yes

2022-10-14 14:25 UTC, closed without merging